In [64]:
import numpy as np
import pandas as pd

In [10]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
new_arr = arr[[0,1,2]]

print(new_arr)


[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [15]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr.base)
print(arr[0:1].base)

None
[[1 2 3]
 [4 5 6]
 [6 7 8]]


Vectorize

In [18]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(np.sin(arr))

def square_if_even(x):
    if x%2==0:
        return x ** 2
    else:
        return x
    
vectorized_square_if_even = np.vectorize(square_if_even)
print(vectorized_square_if_even(arr))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [-0.2794155   0.6569866   0.98935825]]
[[ 1  4  3]
 [16  5 36]
 [36  7 64]]


BroadCasting

In [20]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([1,4,6])
arr1 + arr2

array([[ 2,  6,  9],
       [ 5,  9, 12],
       [ 8, 12, 15]])

In [23]:
arr1 = np.array([[1,3],[4,7],[6,8]])
arr2 = np.array([1,2,3])
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [10]:
arr = np.array([10, 20, 30, 40, 50])
arr[1:4]      # [20 30 40]
print(arr[::-1])    # reverse
print(arr[0:3])

[50 40 30 20 10]
[10 20 30]


In [11]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Rows 0–1, Columns 1–2
matrix[0:2, 1:3]


array([[2, 3],
       [5, 6]])

In [12]:
prices = np.array([100, 200, 300])
discounted = prices * 0.9
print(discounted)

[ 90. 180. 270.]


Reshaping and aggregation 

In [28]:
sales = np.arange(120, 132)

weekly_sales = sales.reshape(3,4) #convert 1D -> 2D
print(weekly_sales)

weekly_total = weekly_sales.sum(axis=0) #row wise
print(weekly_total)

weekly_max = weekly_sales.max(axis=1)
print(weekly_max)

weekly_min  = weekly_sales.min(axis =1)
print (weekly_min)

[[120 121 122 123]
 [124 125 126 127]
 [128 129 130 131]]
[372 375 378 381]
[123 127 131]
[120 124 128]


Advance Slicing

In [44]:
sales = np.array([[100,200,300],
                  [400,500,600],
                  [700,800,900]
                 ])
result1 = sales[0:2, 1:3]
print(result1)

#Extract sales of Store 1 & 2 for Product B and C
#Get all sales greater than 250

result2 = sales[sales > 250]
result2

[[200 300]
 [500 600]]


array([300, 400, 500, 600, 700, 800, 900])

Broadcasting 

In [56]:
Price = np.array([100, 200, 300])
Discount  = np.array([0.1, 0.2, 0.15])

# Calculate Final Price
# Increase price all price by 18%

Final_Price = Price * (1 - Discount)
Final_Price


array([ 90., 160., 255.])

In [59]:

Increase_price = Price * (1 - Discount) * (1 + 25/100)
Increase_price

array([112.5 , 200.  , 318.75])

In [65]:
#After GST not discount
Gst = Price * (1 + 0.30)
Gst

array([130., 260., 390.])

In [85]:
#price more then 500 will get 5% discount
Price = np.array([100, 200, 300, 800, 1200])
Discount  = np.array([10, 20, 15, 25, 25])

Extra_Discount = np.where(Price > 500, 5,0)
Total_Discount = Extra_Discount + Discount
Final_Price = Price * (1 - Total_Discount/100)
print(Final_Price)
Final_Price = Final_Price[Price > 500]
Final_Price

[ 90. 160. 255. 560. 840.]


array([560., 840.])

In [96]:
#Categorical Discount
#Electronics → 10%
#Clothing → 20%
#Grocery → 5%  
Category = np.array(['Electronics' , 'Clothing', 'Grocery'])
Prices = np.array([3999, 4050, 5000])
Discount = {'Electronics': 20, 'Clothing': 30, 'Grocery':10}

Discounts = np.vectorize(Discount.get)(Category)

Final_Price = Prices * ( 1 - Discounts / 100)
Final_Price = np.round(Final_Price, 2)
Final_Price

array([3199.2, 2835. , 4500. ])

Scenario: E-commerce Pricing Engine
Business Rules

Base discount by category

Extra 5% discount if price > ₹2000

Add GST = 18%

Final price ≥ ₹500

Round to 2 decimals

In [110]:
#creating sample data (pandas + numpy)
Data = {
    "Product_id" : [101, 102, 103, 104, 105],
    "Category" : ['Electronics', 'Clothing' , 'Electronics', 'Grocery', 'Clothing'],
    "Price" : [5000, 1000, 800, 2000, 3000]
}

df = pd.DataFrame(Data)
df


Product_id     Category  Price
0         101  Electronics   5000
1         102     Clothing   1000
2         103  Electronics    800
3         104      Grocery   2000
4         105     Clothing   3000

Basic Discount by category

In [111]:
Discount_Map = {
    'Electronics' : 20,
    'Clothing': 10,
    'Grocery': 5
}

df['Base_Discount'] = df['Category'].map(Discount_Map)

Extra discount using vectorized numpy logic

In [113]:
df['Extra_Discount'] = np.where(df['Price'] > 1000, 5, 0)
df['Total_Discount'] = df['Extra_Discount'] + df['Base_Discount']

df['Final_Price'] = df['Price'] * (1 - df['Total_Discount'] / 100)
df['Final_Price']

0    3750.0
1     900.0
2     640.0
3    1800.0
4    2550.0
Name: Final_Price, dtype: float64

In [118]:
Gst = 18
df['Gst_Price'] = df['Final_Price'] * (1 + Gst/100)
df['Gst_Price']

0    4425.0
1    1062.0
2     755.2
3    2124.0
4    3009.0
Name: Gst_Price, dtype: float64

0    3750.18
1     900.18
2     640.18
3    1800.18
4    2550.18
Name: Final_Price, dtype: float64

A/B testing : Discount imapct in Numpy

In [137]:
PriceA = np.array([100, 300, 500, 700])
DiscountA = 10

PriceB = np.array([200, 400, 1000, 800])
DiscountB = 9

Final_PriceA = PriceA * (1 - DiscountA / 100)
Final_PriceB = PriceB * (1 - DiscountB / 100)

lift = (Final_PriceB - Final_PriceA) / Final_PriceA * 100
print("Revenue Lift (%):", np.round(lift, 2))

#the percentage change or relative lift, which provides a normalized and easily interpretable 
#measure of how much a new variant (Product 2) differs from a baseline (Product 1) in an A/B test scenario.


Revenue Lift (%): [102.22  34.81 102.22  15.56]


# Boolean Masking

In [146]:
Price = np.array([1000, 3000, 2000, 1500])
Final_Price = Price.copy()

mask = Price > 2000

Final_Price[mask] = Price[mask] * (1 - 15/100)
Final_Price[~mask] = Price[~mask] * (1 - 5/100)

Final_Price[~mask]

array([ 950, 1900, 1425])

# Vectorized if else

In [147]:
Where = np.where(Price > 2000, Price * 0.85, Price * 0.95)
Where

array([ 950., 2550., 1900., 1425.])

# Vectorized Arithmatic (Chained Operation)

Discount -> Gst -> Rounding in one function

In [158]:
Price = np.array([1000,2000,3000,5000])
Discount = np.array([10, 20, 30, 40])
Gst = 18
final_price = np.round(
    Price * (1 - Discount / 100) * (1 + Gst / 100),
    2
)
final_price

array([1062., 1888., 2478., 3540.])

# Aggregation 

In [169]:
Revenue = np.sum(final_price) #
print(Revenue)

AOV = np.mean(final_price) #Average order value
print(AOV)

Percentage = np.percentile(final_price, 90)
print(Percentage)

8968.0
2242.0
3221.4


# Vectorized time series

In [173]:
sales = np.array([100, 120, 150, 130])
uplift = np.array([1.0, 1.1, 1.2, 1.05])

adjusted_sales = sales * uplift
adjusted_sales

array([100. , 132. , 180. , 136.5])

array([100. , 132. , 180. , 136.5])